name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose --all-targets

      - name: Build tests (ensures fastga-rs is compiled)
        run: cargo test --no-run --verbose

      - name: Set FastGA binary path
        run: |
          # Find the FastGA binary (not just the first fastga-rs directory)
          FASTGA_BIN=$(find target/debug/build -name "FastGA" -type f | head -1)
          if [ -f "$FASTGA_BIN" ]; then
            FASTGA_DIR=$(dirname "$FASTGA_BIN")
            echo "Found FastGA binaries in: $FASTGA_DIR"
            echo "$FASTGA_DIR" >> $GITHUB_PATH
          else
            echo "ERROR: FastGA binary not found!"
            find target/debug/build -name "fastga-rs-*" -type d || true
            exit 1
          fi

      - name: Run tests
        run: cargo test --verbose

      - name: Set FastGA binary path (release)
        run: |
          # Find the FastGA binary in release build directory
          FASTGA_BIN=$(find target/release/build -name "FastGA" -type f | head -1)
          if [ -f "$FASTGA_BIN" ]; then
            FASTGA_DIR=$(dirname "$FASTGA_BIN")
            echo "Found FastGA release binaries in: $FASTGA_DIR"
            echo "$FASTGA_DIR" >> $GITHUB_PATH
          else
            echo "Warning: FastGA release binaries not found, trying to build..."
            cargo build --release
            FASTGA_BIN=$(find target/release/build -name "FastGA" -type f | head -1)
            if [ -f "$FASTGA_BIN" ]; then
              FASTGA_DIR=$(dirname "$FASTGA_BIN")
              echo "$FASTGA_DIR" >> $GITHUB_PATH
            fi
          fi

      - name: Run tests (release mode)
        run: cargo test --release --verbose

      - name: Check for forbidden files
        run: |
          # Check for files that should never be committed
          if git ls-tree -r HEAD --name-only | grep -E '\.(fa|fasta|paf|gdb|ktab|bps)$' | grep -v 'data/scerevisiae8.fa.gz'; then
            echo "ERROR: Found forbidden data files in repository!"
            echo "Only data/scerevisiae8.fa.gz is allowed"
            exit 1
          fi

  build:
    name: Build Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Build (all features)
        run: cargo build --verbose --all-features